- defaultTab: nodes
  description: ''
  executionEnabled: true
  id: 37d90913-5026-4a18-b795-2526c27b52e7
  loglevel: INFO
  name: ejecutar_playbook
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: entorno1
  nodesSelectedByDefault: true
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        ansible-become: 'false'
        ansible-binaries-dir-path: /home/rundeck/.local/bin
        ansible-playbook: /home/rundeck/server/data/ansible/playbooks/playbook1.yaml
        ansible-ssh-auth-type: password
        ansible-ssh-passphrase-option: option.password
        ansible-ssh-password-storage-path: keys/project/prueba_ansible/contenedores_pass
        ansible-ssh-use-agent: 'false'
        ansible-ssh-user: root
      nodeStep: true
      type: com.batix.rundeck.plugins.AnsiblePlaybookWorflowNodeStep
    keepgoing: true
    strategy: node-first
  uuid: 37d90913-5026-4a18-b795-2526c27b52e7

